### ISSUE TITLE
MediaQuery still necessary?

### ISSUE THREAD

**Issue by xErik** [LastMonopoly/scaled_app#10]
`Flutter (Channel stable, 3.13.2)`

Thank you for the package, it works very well in my case.

I initialize the package as follows:

```dart
final widgetsBinding = ScaledWidgetsFlutterBinding.ensureInitialized(
  scaleFactor: (deviceSize) {
    const double widthOfDesign = 360;
    return deviceSize.width / widthOfDesign;
  },
);
```

But the code below seems not to be necessary when developing using local Chrome. Everything is already correctly scaled.

```dart
MediaQuery(
        data: MediaQuery.of(context).scale(),
        child: Scaffold( ... )
)
```

Is that just a local quirk and is the code indeed necessary?
Or is that the legacy way of using the package?
Or did I misread the docs and this code was never necessary?

Thanks you!

**Comment by LastMonopoly** [comment]
Hi @xErik 
If u use mediaQueryData in your app, then please scale ur mediaQueryData on top of your app
Otherwise, MediaQuery.of(context) will give u the original MediaQueryData before scaling
