### ISSUE TITLE
Superclass has no method named 'createViewConfiguration'.

### ISSUE THREAD

**Issue by m-zarif** [LastMonopoly/scaled_app#11]
/C:/Users/UserName/AppData/Local/Pub/Cache/hosted/pub.dev/scaled_app-2.1.0/lib/scaled_app.dart:81:20: Error: Superclass has no method named 'createViewConfiguration'.
      return super.createViewConfiguration();
                   ^^^^^^^^^^^^^^^^^^^^^^^

Flutter (Channel stable, 3.16.0, on Microsoft Windows [Version 10.0.22621.2715], locale en-US)
    • Flutter version 3.16.0 on channel stable at flutter-sdk-address
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (4 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

**Comment by LastMonopoly** [comment]
Will take a look

**Comment by chitkosarvesh** [comment]
I started having this issue too recently!
Strangely, it happens ONLY on the appcenter builds and nowhere else.
`[✓] Flutter (Channel stable, 3.16.0, on macOS 11.7.10 20G1427 darwin-x64, locale en)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    ✗ Flutter requires Xcode 14 or higher.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] Connected device (2 available)
[✓] Network resources`

**Comment by rologr35** [comment]
@LastMonopoly https://github.com/LastMonopoly/scaled_app/pull/12 this is a PR with a minor change to adapt the lib to the new RenderView class.

**Comment by LastMonopoly** [comment]
Thank you @rologr35 
The bug is fixed in 2.2.0
