### ISSUE TITLE
Feature request: scaling only a route(page/screen)

### ISSUE THREAD

**Issue by Somtobro** [LastMonopoly/scaled_app#19]
Feature request: scaling only a route(page/screen) instead of the whole app. Most usecases will need this.

**Comment by LastMonopoly** [comment]
README mentioned "Optionally, update ScaledWidgetsFlutterBinding.instance.scaleFactor to enable / disable scaling on demand."

See this example https://github.com/LastMonopoly/scaled_app/blob/master/example/lib/scale_the_app.dart

**Comment by Somtobro** [comment]
Thanks for this innovative package...I'm sure you're a problem solver in real life.peace
