### ISSUE TITLE
Can we have different scale factor/width for landscape

### ISSUE THREAD

**Issue by prateekmedia** [LastMonopoly/scaled_app#3]
Currently If user does landscape then the portrait scaling is applied and hence the user sees too much zoomed in UI as opposed to standard landscape UI. Can we have different scale parameter for landscape, Thanks!

**Comment by LastMonopoly** [comment]
@prateekmedia 
see my example here: https://github.com/LastMonopoly/scaled_app/blob/master/example/lib/main.dart
use scaleFactorCallback for your custom scaling factor
