### ISSUE TITLE
Getting error when try to launch the app

### ISSUE THREAD

**Issue by booooohdan** [LastMonopoly/scaled_app#7]
I use a 1.1.0 version
<img width="919" alt="Знімок екрана 2023-06-22 о 00 04 21" src="https://github.com/LastMonopoly/scaled_app/assets/30977443/ca96f331-b4fd-4ec9-b381-b12025d1eb9f">

**Comment by LastMonopoly** [comment]
What is your Flutter version @booooohdan 
For  Flutter 3.10.x, use scaled_app 2.0.0

**Comment by booooohdan** [comment]
@LastMonopoly I used 3.7.9 and currently can't update to 3.10.x

**Comment by LastMonopoly** [comment]
@booooohdan 

Could you please provide a minimal reproducible example?

Or run my `example/` project from this branch https://github.com/LastMonopoly/scaled_app/tree/3.7.12
