### ISSUE TITLE
flutter 3.13 build failed

### ISSUE THREAD

**Issue by selvam920** [LastMonopoly/scaled_app#8]
/C:/Users/sksso/AppData/Local/Pub/Cache/hosted/pub.dev/scaled_app-2.0.0/lib/scaled_app.dart(118,53): error GC2F972A8: The argument type 'double' can't be assigned to the parameter type 'double? Function(int)'. [E:\sksmarket\sksmarket\build\windows\flutter\flutter_assemble.vcxproj]

**Comment by selvam920** [comment]
Flutter (Channel beta, 3.13.0-0.1.pre, on Microsoft Windows [Version 10.0.22621.1992], locale en-IN)

**Comment by selvam920** [comment]
Hi, please check this issue?

**Comment by selvam920** [comment]
Hi any update on this?

**Comment by selvam920** [comment]
any fixes? waiting for this?

**Comment by cumhurkose** [comment]
@selvam920 
I just edit this code line and it's fix.  
scaled_app.dart(118,53)
-  _pendingPointerEvents.addAll(PointerEventConverter.expand(packet.data, return devicePixelRatioScaled, ));
+ _pendingPointerEvents.addAll(PointerEventConverter.expand(packet.data, (viewId) { return devicePixelRatioScaled; }, ));

**Comment by LastMonopoly** [comment]
Thanks a lot for your help @selvam920 @cumhurkose 

Check out the scaled_app: ^2.1.0
